//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cities_States.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeID { get; set; }
        [Required(ErrorMessage = "Full Name is required")] // Add Required attribute here

        public string FullName { get; set; }
        public string FathersName { get; set; }
        public string Designation { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string PAN { get; set; }
        public string Aadhar { get; set; }
        public string MobileNumber { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public string UAN { get; set; }
        public string PFNumber { get; set; }
        public bool SalaryBelow21K { get; set; }
        public string ESINumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string IFSC { get; set; }
        public int ClientID { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime DateOfDeployment { get; set; }
        public string Photograph { get; set; }
        public string MaritalStatus { get; set; }

        public bool? Transferred { get; set; }
        public bool IsTransferred => Transferred ?? false;

        public string ClientName { get; set; }
        public string ClientLocation { get; set; }
        public Nullable<bool> InactiveStatus { get; set; }
        public Nullable<System.DateTime> DateOfExit { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
